import { readFile, stat, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parse, type Node } from "acorn";
import { ancestor as walkAncestor } from "acorn-walk";

export type MigrateOptions = {
  scenarioDir: string;
  outputFileName?: string;
  force?: boolean;
};

export type MigrateResult = {
  outputPath: string;
  testCount: number;
  assertCount: number;
  warnings: string[];
};

const ASSERT_MAP: Record<string, (args: string) => string> = {
  assertEquals: (args) => {
    const parts = splitTopLevel(args);
    if (parts.length < 2) return `// assertEquals(${args})`;
    return `expect(${parts[0]}).toBe(${parts[1]})`;
  },
  assertTrue: (args) => `expect(${splitTopLevel(args)[0]}).toBeTruthy()`,
  assertFalse: (args) => `expect(${splitTopLevel(args)[0]}).toBeFalsy()`,
  assertNull: (args) => `expect(${splitTopLevel(args)[0]}).toBeNull()`,
  assertNotNull: (args) => `expect(${splitTopLevel(args)[0]}).not.toBeNull()`,
  assertDefined: (args) => `expect(${splitTopLevel(args)[0]}).toBeDefined()`,
  assertContains: (args) => {
    const parts = splitTopLevel(args);
    return `expect(${parts[0]}).toContain(${parts[1]})`;
  },
  assertEmpty: (args) => `expect(${splitTopLevel(args)[0]}).toHaveLength(0)`,
  assertNotEmpty: (args) => `expect(${splitTopLevel(args)[0]}.length).toBeGreaterThan(0)`,
  assertLength: (args) => {
    const parts = splitTopLevel(args);
    return `expect(${parts[0]}).toHaveLength(${parts[1]})`;
  },
};

function splitTopLevel(args: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let inStr: string | null = null;
  let start = 0;
  for (let i = 0; i < args.length; i++) {
    const ch = args[i];
    if (inStr) {
      if (ch === inStr && args[i - 1] !== "\\") inStr = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      inStr = ch;
      continue;
    }
    if (ch === "(" || ch === "[" || ch === "{") depth++;
    if (ch === ")" || ch === "]" || ch === "}") depth--;
    if (ch === "," && depth === 0) {
      parts.push(args.slice(start, i).trim());
      start = i + 1;
    }
  }
  if (start < args.length) parts.push(args.slice(start).trim());
  return parts;
}

/**
 * Простейший миграционный конвертер.
 *
 * 1. Парсит исходник сценария через acorn.
 * 2. Находит function-declarations с именами `test<N>_*`, `runXxxTests`.
 * 3. Для каждой `test*` создаёт `it('<имя из камеллкейса>', ...)`.
 * 4. Внутри тела заменяет вызовы `assertEquals` и т.п. на `expect(...).to*`.
 *
 * Это эвристический конвертер — он может оставлять предупреждения.
 * Финальный результат всё равно требует ручной проверки.
 */
export async function migrateScenario(opts: MigrateOptions): Promise<MigrateResult> {
  const warnings: string[] = [];
  const sourceFile = await pickSourceFile(opts.scenarioDir);
  const source = await readFile(sourceFile, "utf-8");
  const ast = parse(source, { ecmaVersion: 2020, sourceType: "script", locations: true }) as Node;

  type FnDecl = { name: string; body: string };
  const tests: FnDecl[] = [];
  let assertCount = 0;

  walkAncestor(ast as unknown as Parameters<typeof walkAncestor>[0], {
    FunctionDeclaration(node) {
      const fn = node as Node & {
        id?: { name?: string };
        body?: Node & { start?: number; end?: number };
      };
      const name = fn.id?.name ?? "";
      if (!/^test\d+_/.test(name)) return;
      const body = fn.body;
      if (!body || typeof body.start !== "number" || typeof body.end !== "number") return;
      const bodyText = source.slice(body.start + 1, body.end - 1);
      const converted = convertAssertions(bodyText, (n) => {
        assertCount += n;
      });
      tests.push({ name, body: indent(converted, 4) });
    },
  });

  if (tests.length === 0) {
    warnings.push("No functions matching /^test\\d+_/ found");
  }

  const outputPath = resolve(opts.scenarioDir, ".tests", opts.outputFileName ?? "migrated.test.js");
  let exists = false;
  try {
    await stat(outputPath);
    exists = true;
  } catch {
    /* ok */
  }
  if (exists && !opts.force) {
    warnings.push(`Output exists (use --force to overwrite): ${outputPath}`);
    return { outputPath, testCount: tests.length, assertCount, warnings };
  }

  const body = tests
    .map((t) => `  it(${JSON.stringify(humanize(t.name))}, () => {\n${t.body}\n  });`)
    .join("\n\n");

  const out = `// Auto-generated by scenario-sim migrate. Review and adjust as needed.\n\ndescribe(${JSON.stringify(scenarioName(opts.scenarioDir) + " — migrated")}, () => {\n${body}\n});\n`;

  await writeFile(outputPath, out, "utf-8");
  return { outputPath, testCount: tests.length, assertCount, warnings };
}

async function pickSourceFile(scenarioDir: string): Promise<string> {
  // Возьмём первый .js в source/, который содержит "function test"
  const { readdir } = await import("node:fs/promises");
  const sourceDir = resolve(scenarioDir, "source");
  const entries = await readdir(sourceDir);
  for (const f of entries) {
    if (!f.endsWith(".js")) continue;
    const full = resolve(sourceDir, f);
    const s = await readFile(full, "utf-8");
    if (s.includes("function test") || s.includes("runTests")) return full;
  }
  if (entries.length === 0) throw new Error(`No JS in ${sourceDir}`);
  return resolve(sourceDir, entries[0]!);
}

function convertAssertions(source: string, onAssert: (n: number) => void): string {
  let count = 0;
  const out = source.replace(/\b(assert\w+)\s*\(([\s\S]*?)\)\s*;?/g, (whole, fn: string, args: string) => {
    const mapper = ASSERT_MAP[fn];
    if (!mapper) return whole;
    count++;
    return `${mapper(args)};`;
  });
  onAssert(count);
  return out;
}

function indent(text: string, n: number): string {
  const pad = " ".repeat(n);
  return text
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

function humanize(name: string): string {
  // testN_FooBar → "FooBar" → "Foo Bar"
  const stripped = name.replace(/^test\d+_/, "");
  return stripped.replace(/([a-z])([A-Z])/g, "$1 $2");
}

function scenarioName(dir: string): string {
  return dir.split(/[\\/]/).pop() ?? "scenario";
}
